version: '3.7'

services:
  frontend:
    image: michelm2306/list-frontend:1.0
    container_name: ourspace_frontend
    ports:
      - 3000:80
    depends_on:
      - backend
    networks:
      - ourspace-network
    environment:
      - VITE_BASEURL=http://backend:8080
      - VITE_LANGUAGE=de
    volumes:
      - ./src:/app/src
  backend:
    image: michelm2306/list-backend:1.0
    container_name: ourspace_backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - 8080:8080
    depends_on:
      - postgres
    networks:
      - ourspace-network
  postgres:
    image: postgres:15-alpine
    container_name: ourspace_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ourspace-network

networks:
  ourspace-network:
    driver: bridge

volumes:
  postgres_data:
